apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-scripts-api-enriquecimento
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/rodrigocosta/Documents/GitHub/tutoriais/enriquecimento/kubernetes/volumes/db-scripts-api-enriquecimento"
