version: '3.9'

services:
  redis:
    image: redis
    container_name: redis-authorization-server
    ports:
      - "6379:6379"
#  app:
#    build:
#      dockerfile: ./Dockerfile
#      context: .
#    platform: linux/arm64/v8
#    image: authorization-server
#    container_name: app-authorization-server
#    ports:
#      - '8081:8081'
#    networks:
#      - development-network
networks:
  development-network:
    driver: bridge
