spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8085/oauth/check_token
          client-id: myclient-id
          client-secret: myclient-secret