version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql-api-enriquecimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: "api_enriquecimento"
      MYSQL_ROOT_HOST: '%'
    #    volumes:
    #      - './data/enriquecimento/backup:/var/lib/mysql'
    # forma alternativa ao import.sql para inseriri dados na tabela
    #      - './data/enriquecimento:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
    networks:
      - dev_network

  api-enriquecimento:
    image: api-enriquecimento
    # quando subi com scalle deu erro deixar o container name e o nome do serviço. Mesmo com nomes diferentes ainda sim deu erro
    #    container_name: api-enriquecimento
    #pode usar o nome do serviço ou o nome do container do mysql no command
    command: [ "/wait-for-it.sh", "mysql-api-enriquecimento:3306", "-t", "60", "--", "java", "-jar", "app.jar" ]
    build: api-enriquecimento
    platform: linux/arm64/v8
    environment:
      API_ENRIQUECIMENTO_MYSQL_HOST: mysql-api-enriquecimento
      AUTHORIZATION_SERVER_HOST: authorization-server
    # remover ports para poder executar compose up --scalle app-java=2
    #    ports:
    #      - '8080:8080'
    networks:
      - dev_network
    depends_on:
      - mysql

  api-enriquecimento-prox:
    build: ./nginx
    image: api-enriquecimento-prox
    ports:
      - '80:80'
    networks:
      - dev_network
    depends_on:
      - api-enriquecimento

  adminer:
    image: adminer
    container_name: adminer-api-enriquecimento
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - '8085:8080'
    networks:
      - dev_network

  mongo:
    image: mongo
    container_name: mongo-api-enriquecimento
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_DATABASE=Auditavel
#      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - dev_network

  mongo-express:
    container_name: mongo-express-api-enriquecimento
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - dev_network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-api-enriquecimento
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - '8091:8081'
    volumes:
      - ./data:/data/db

  redis:
    image: redis
    container_name: redis-authorization-server
    ports:
      - "6379:6379"
    networks:
      - dev_network

  authorization-server:
    image: authorization-server
    build: authorization-server
    platform: linux/arm64/v8
    #container_name: authorization-server
    environment:
      AUTHORIZATION_SERVER: redis
    ports:
      - '8081:8081'
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
