version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql-api-enriquecimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: "api_enriquecimento"
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - dev_network
#
#  api-enriquecimento:
#    image: i_api-enriquecimento
#    command: [ "/wait-for-it.sh", "mysql-api-enriquecimento:3306", "-t", "60", "--", "java", "-jar", "app.jar" ]
#    platform: linux/arm64/v8
#    environment:
#      API_ENRIQUECIMENTO_MYSQL_HOST: mysql-api-enriquecimento
#      AUTHORIZATION_SERVER_HOST: authorization-server
#    networks:
#      - dev_network
#    depends_on:
#      - mysql
#
  api-enriquecimento-prox:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: api-enriquecimento-prox
    ports:
      - '80:80'
    networks:
      - dev_network
    depends_on:
      - api-enriquecimento

  adminer:
    image: adminer
    container_name: adminer-api-enriquecimento
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - '8085:8080'
    networks:
      - dev_network

  mongo:
    image: mongo
    container_name: mongo-api-enriquecimento
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_DATABASE=Auditavel
#      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - dev_network

  mongo-express:
    container_name: mongo-express-api-enriquecimento
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - dev_network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-api-enriquecimento
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - '8091:8081'
    volumes:
      - ./data:/data/db

  redis:
    image: redis
    container_name: redis-authorization-server
    ports:
      - "6379:6379"
    networks:
      - dev_network

#  authorization-server:
#    image: authorization-server
#    build: authorization-server
#    platform: linux/arm64/v8
#    #container_name: authorization-server
#    environment:
#      AUTHORIZATION_SERVER: redis
#    ports:
#      - '8081:8081'
#    networks:
#      - dev_network

networks:
  dev_network:
    driver: bridge
