apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-scripts-api-enriquecimento
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
