apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-bkp-api-enriquecimento
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
