apiVersion: v1
kind: Service
metadata:
  name: svc-np-api-enriquecimento
spec:
  type: NodePort
  selector:
    app: pod-api-enriquecimento
  ports:
  - port: 8080
    #targetPort: <Target Port>
    nodePort: 30003

