version: '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql
    container_name: mysql-ms-enriquecimento
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: "ms_enriquecimento"
      MYSQL_ROOT_HOST: '%'
    #    volumes:
    #      - './data/enriquecimento/backup:/var/lib/mysql'
    #      - './data/enriquecimento:/docker-entrypoint-initdb.d'
    ports:
      - '3307:3306'
    networks:
      - development-network
networks:
  development-network:
    driver: bridge
