spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${AUTHORIZATION_SERVER_HOST:http://localhost:8081}/oauth/check_token
          client-id: ResourcerServerClientID
          client-secret: ResourcerServerClientSecret
  datasource:
    username: ${MYSQL_ROOT_PASSWORD:root}
    url: ${API_ENRIQUECIMENTO_MYSQL_HOST:jdbc:mysql://localhost:3306}/${MYSQL_DATABASE:api_enriquecimento}?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${MYSQL_PASSWORD:root}
  jpa:
    #generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'