server:
  port: 8081

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/api_enriquecimento?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
  jpa:
    #generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    hibernate:
      #ddl-auto: create
    show-sql: 'true'
