spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://${AUTHORIZATION_SERVER_HOST:localhost}:${AUTHORIZATION_SERVER_PORT:8081}/oauth/check_token
          client-id: ResourcerServerClientID
          client-secret: ResourcerServerClientSecret
  datasource:
    username: ${API_ENRIQUECIMENTO_MYSQL_USER:root}
    url: jdbc:mysql://${API_ENRIQUECIMENTO_MYSQL_HOST:localhost}:${API_ENRIQUECIMENTO_MYSQL_PORT:3306}/${API_ENRIQUECIMENTO_MYSQL_DATABASE:api_enriquecimento}?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${API_ENRIQUECIMENTO_MYSQL_PASSWORD:root}
  jpa:
    #generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    hibernate:
#      ddl-auto: create
    show-sql: 'true'


