server:
  port: 8080

spring:

  datasource:
#*******************H2*********************************#
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#*******************H2*********************************#

#*******************MYSQL*********************************#
    url: jdbc:mysql://${API_ENRIQUECIMENTO_MYSQL_HOST:localhost}:${API_ENRIQUECIMENTO_MYSQL_PORT:3306}/${API_ENRIQUECIMENTO_MYSQL_DATABASE:api_enriquecimento}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${API_ENRIQUECIMENTO_MYSQL_USER:root}
    password: ${API_ENRIQUECIMENTO_MYSQL_PASSWORD:root}
#*******************MYSQL*********************************#

  jpa:
    # combinado com o arquivo import.sql é feito insert na tabela
    generate-ddl: 'true'
#*******************H2*********************************#
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#*******************H2*********************************#

#*******************MYSQL*********************************#
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
#*******************MYSQL*********************************#

#*******************H2*********************************#
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2
#*******************H2*********************************#

  data:
      mongodb:
          uri: mongodb://${API_ENRIQUECIMENTO_MONGODB_HOST:localhost}:${API_ENRIQUECIMENTO_MONGODB_PORT:27017}/${API_ENRIQUECIMENTO_MONGODB_DATABASE:Auditavel}

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://${AUTHORIZATION_SERVER_HOST:localhost}:${AUTHORIZATION_SERVER_PORT:8081}/oauth/check_token
          client-id: ResourcerServerClientID
          client-secret: ResourcerServerClientSecret

