version: "3"

services:

    dbuser:
        container_name: mongo-dbuser
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_DATABASE=Audit
            - MONGO_INITDB_ROOT_PASSWORD=pass
        networks:
            - development-network
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db

    mongo-express-dbuser:
        container_name: mongo-express-dbuser
        image: mongo-express
        depends_on:
            - dbuser
        networks:
            - development-network
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo-dbuser
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=pass
        ports:
            - '8081:8081'
        volumes:
            - ./data:/data/db

networks:
    development-network:
        driver: bridge