version: "3.7"

services:
    db:
        container_name: mongo-tutorial
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_DATABASE=Tutorial
            - MONGO_INITDB_ROOT_PASSWORD=pass
        networks:
            - mongo-tutorial-network
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db

    mongo-express:
        container_name: mongo-express-tutorial
        image: mongo-express
        depends_on:
            - db
        networks:
            - mongo-tutorial-network
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo-tutorial
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=pass
        ports:
            - '8081:8081'
        volumes:
            - ./data:/data/db

networks:
    mongo-tutorial-network:
        driver: bridge