spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_enriquecimento?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
feign:
  client:
    config:
      default:
        readTimeout: '50000'
        connectTimeout: '50000'
server:
  port: '8091'
